"use client";

import React from "react";
import { PoapEventData } from "@/lib/contracts/client";
import {
  CheckCircle2,
  AlertCircle,
  KeyRound,
  Users,
  Globe,
} from "lucide-react";

export interface EligibilityCardProps {
  event: PoapEventData;
  isConnected: boolean;
  userAddress?: `0x${string}`;
  hasClaimed: boolean;
  isAllowlistEligible?: boolean;
  hasValidSignature?: boolean;
  isCreator?: boolean;
}

export function EligibilityCard({
  event,
  isConnected,
  userAddress,
  hasClaimed,
}: EligibilityCardProps) {
  if (!isConnected || !userAddress) {
    return (
      <div className="p-4 rounded-2xl bg-neutral-50 dark:bg-neutral-900 border border-neutral-200/80 dark:border-neutral-800 flex items-start gap-3 text-left">
        <AlertCircle className="w-5 h-5 text-neutral-400 shrink-0 mt-0.5" />
        <div>
          <div className="text-xs font-semibold text-neutral-900 dark:text-white">
            Eligibility Status: Wallet Disconnected
          </div>
          <p className="text-xs text-neutral-500 dark:text-neutral-400 mt-0.5 leading-relaxed">
            Connect your Ethereum wallet to verify claim eligibility for this event.
          </p>
        </div>
      </div>
    );
  }

  if (hasClaimed) {
    return (
      <div className="p-4 rounded-2xl bg-lime-50 dark:bg-lime-950/40 border border-lime-200 dark:border-lime-800 flex items-start gap-3 text-left">
        <CheckCircle2 className="w-5 h-5 text-lime-600 dark:text-lime-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-lime-900 dark:text-lime-200">
              Badge Collected & Verified
            </span>
            <span className="bg-lime-200 dark:bg-lime-900 text-lime-900 dark:text-lime-200 text-[10px] font-mono font-bold px-2 py-0.5 rounded-full uppercase">
              Owned
            </span>
          </div>
          <p className="text-xs text-lime-800 dark:text-lime-300 leading-relaxed">
            You already hold 1 token for Event #{event.eventId} in your connected wallet. Each address is limited to 1 token by contract rules.
          </p>
        </div>
      </div>
    );
  }

  if (event.isPublic) {
    return (
      <div className="p-4 rounded-2xl bg-white dark:bg-neutral-900 border border-neutral-200/80 dark:border-neutral-800 flex items-start gap-3 text-left shadow-card">
        <Globe className="w-5 h-5 text-blue-600 dark:text-blue-400 shrink-0 mt-0.5" />
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-neutral-900 dark:text-white">
              Eligible — Public Mint
            </span>
            <span className="bg-emerald-100 dark:bg-emerald-950/60 text-emerald-800 dark:text-emerald-300 text-[10px] font-mono font-semibold px-2 py-0.5 rounded-full uppercase">
              Open to All
            </span>
          </div>
          <p className="text-xs text-neutral-500 dark:text-neutral-400 mt-0.5 leading-relaxed">
            This event is currently open for public minting on Base Sepolia.
          </p>
        </div>
      </div>
    );
  }

  const hasAllowlist =
    event.allowlistRoot &&
    event.allowlistRoot !== "0x0000000000000000000000000000000000000000000000000000000000000000";

  if (hasAllowlist) {
    return (
      <div className="p-4 rounded-2xl bg-white dark:bg-neutral-900 border border-neutral-200/80 dark:border-neutral-800 flex items-start gap-3 text-left shadow-card">
        <Users className="w-5 h-5 text-purple-600 dark:text-purple-400 shrink-0 mt-0.5" />
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-neutral-900 dark:text-white">
              Allowlist Protected
            </span>
            <span className="bg-purple-100 dark:bg-purple-950/60 text-purple-800 dark:text-purple-300 text-[10px] font-mono font-semibold px-2 py-0.5 rounded-full uppercase">
              Merkle Tree
            </span>
          </div>
          <p className="text-xs text-neutral-500 dark:text-neutral-400 mt-0.5 leading-relaxed">
            Claiming requires an authorized Merkle branch proof hash generated by the event host.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 rounded-2xl bg-white dark:bg-neutral-900 border border-neutral-200/80 dark:border-neutral-800 flex items-start gap-3 text-left shadow-card">
      <KeyRound className="w-5 h-5 text-neutral-600 dark:text-neutral-400 shrink-0 mt-0.5" />
      <div>
        <div className="flex items-center gap-2">
          <span className="text-xs font-semibold text-neutral-900 dark:text-white">
            Signature Claim Mode
          </span>
        </div>
        <p className="text-xs text-neutral-500 dark:text-neutral-400 mt-0.5 leading-relaxed">
          Scan the QR pass at the live event to receive an authorized creator signature.
        </p>
      </div>
    </div>
  );
}
